USE [master]
GO
CREATE DATABASE [DevLearn] 
GO
USE [DevLearn] 
GO

ALTER DATABASE [DevLearn] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DevLearn] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DevLearn] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DevLearn] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DevLearn] SET ARITHABORT OFF 
GO
ALTER DATABASE [DevLearn] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DevLearn] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DevLearn] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DevLearn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DevLearn] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DevLearn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DevLearn] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DevLearn] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DevLearn] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DevLearn] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DevLearn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DevLearn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DevLearn] SET TRUSTWORTHY ON 
GO
ALTER DATABASE [DevLearn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DevLearn] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DevLearn] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DevLearn] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DevLearn] SET RECOVERY FULL 
GO
ALTER DATABASE [DevLearn] SET  MULTI_USER 
GO
ALTER DATABASE [DevLearn] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DevLearn] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DevLearn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DevLearn] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DevLearn] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DevLearn] SET QUERY_STORE = OFF
GO
USE [DevLearn]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [DevLearn]
GO

CREATE ROLE [rmq]
GO


CREATE ASSEMBLY [SqlClr]
FROM 'C:\Code\DevLearn\SqlClr\bin\Debug\SqlClr.dll' 
WITH PERMISSION_SET = UNSAFE
GO


CREATE SCHEMA [rmq]
GO


CREATE PROCEDURE [dbo].[pr_clr_PostRabbitMsg]
	@msg [nvarchar](max)
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [SqlClr].[SqlClr.RabbitMqSqlServer].[Pr_clr_PostRabbitMsg]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[Scores_On_After_Insert]
   ON  [dbo].[Score]
   AFTER INSERT
AS 
BEGIN
	DECLARE @RetVal NVARCHAR(MAX)
    SELECT @RetVal = (
		SELECT inserted.*, HomeTeam as 'HomeTeam', AwayTeam as 'AwayTeam'
		FROM inserted 
		INNER JOIN dbo.[Event]
		ON [Event].EventId = inserted.EventId
		FOR JSON PATH)

	EXEC dbo.pr_clr_PostRabbitMsg @RetVal
END
GO

ALTER TABLE [dbo].[Score] ENABLE TRIGGER [Scores_On_After_Insert]
GO

USE [master]
GO

ALTER DATABASE [DevLearn] SET  READ_WRITE 
GO


-- ENABLE CLR
sp_configure @configname=clr_enabled, @configvalue=1
GO

RECONFIGURE
Go
